### PR TITLE
30 rfswarm agent seleniumlibrary image

### PR DESCRIPTION
**Pull request by Maresther-B**
I've just finished Selenium Library image. 
If you guy want to do a quick check you can use this simple script example:

**Selenim_image_test.robot file**

*** Settings ***
Documentation     This  test file is used to make a quick test
...               with rfswarm agent selenium image

Suite setup       Open a website     ${URL}
Suite Teardown    Close all browsers

Resource          keywords.robot

*** Variables ***
${URL}        http://www.google.com
${BROWSER}    /usr/bin/chromedriver
${research bar}    //*[@id="APjFqb"]
${search term}     docker

*** Test Cases ***
User launch a website
    [Documentation]    This test is used to open a website
    Given the wesite application is correctly launched

**Kewords.robot file**

*** Settings ***
Documentation    This file is a ressource file where keywords are
...              gathering.   

Library    SeleniumLibrary

*** Variables ***
${DOWNLOADDIRECTORY}    /scr/
${BROWSER}              /usr/bin/chromedriver
${SEARCH FORM}         .//form
${RESEARCH_BAR}        //*[@id="APjFqb"]  
${INPUT_TEXTE}         healthy 

*** Keywords ***

Open a Web site
    [Documentation]    This keyword is used to open a website with Selenium browser
    [Arguments]   ${URL}
    ${options}=  Evaluate  sys.modules['selenium.webdriver'].ChromeOptions()  sys
    Call Method  ${options}  add_argument  --disable-notifications
    Call Method  ${options}  add_argument  --disable-infobars
    Call Method  ${options}  add_argument  --disable-extensions
    Call Method  ${options}  add_argument  --no-sandbox
    Call Method  ${options}  add_argument  --headless
    Call Method  ${options}  add_argument  --disable-gpu
    Call Method  ${options}  add_argument  --disable-dev-shm-usage
    Open Browser  ${URL}  Chrome  options=${options}
    #Maximize Browser Window
    Set Window Size    1920    1080

the wesite application is correctly launched
    [Documentation]    This keyword is used to check if the website is
    ...                succefuly launched
    Log To Console      Launch google  wesite
    Click Button    xpath://*[@id="L2AGLb"]
    Sleep    3
    Wait Until Element Is Visible    xpath:${SEARCH FORM}     5    
    Wait Until Element Is Visible    xpath:${RESEARCH_BAR}    5     
    capture page screenshot

a user makes a query in the google search bar

the search term is succefuly found in the current page

### CODE REVIEW

**Comment by damies13** [comment]
Just an observation, nothing that will prevent you publishing this image:
I don't think you need `agent/sshlibrary/entrypoint.sh`, or `agent/seleniumlibrary-chrome/entrypoint.sh`, as:
- `entrypoint.sh` is already in the base image,
- there's no change to `entrypoint.sh`,
- there is no command in your sshlibrary and seleniumlibrary-chrome Dockerfile's to copy the `entrypoint.sh` in that directory over the one in the base image

Unless you actually needed to change the entrypoint file for the image, there's no need to replace it, just use the one included in the base image.

**Review by damies13 — APPROVED** [review]

**Review by KseniaYa — APPROVED** [review]

**Review by damies13 — COMMENTED** [review]
The tests you put in the tests folder, go to google, so that will fail in the rare (admittedly extremely rare) situation when google is down, it might be better to goto `https://github.com` which is more likely to be up if the runner is running, i.e. if github is down, you probably weren't able to checking your change and trigger the github action

**Comment by damies13** [comment]
This might be useful for creating a test case for the ssh library agent : https://sdf.org/?signup

No need to to create an account, login as U: new P: new, follow the prompts, when it asks for a username, just press enter and then logout

**Comment by Maresther-B** [comment]
> This might be useful for creating a test case for the ssh library agent : https://sdf.org/?signup
> 
> No need to to create an account, login as U: new P: new, follow the prompts, when it asks for a username, just press enter and then logout

Thanks Dave for the suggestion. I'll create a issue for this and work on it on the week end

**Pull request merged**
